mpc_node:
  ros__parameters:
    waypoint_csv: "/home/yxjacksn/ese6150/mpc_ws/src/mpc_pkg/data/waypoints.csv"
    horizon: 10
    dt: 0.1
    wheelbase: 0.3302
    q_x: 10.0
    q_y: 10.0
    q_theta: 2.0
    q_v: 10.0
    r_delta: 1.0
    r_a: 1.0
    r_d_delta: 5.0
    r_d_a: 1.0
    delta_max: 0.4189
    v_min: 0.0
    v_max: 2.5
    a_max: 2.0
    lookahead_idx: 1
    publish_waypoints: true
    control_rate: 20.0
